// Database type definitions for the Georgian Distribution System
// This file is automatically generated from Supabase schema
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// Core user types
export type UserRole = 'admin' | 'restaurant' | 'driver' | 'demo'
export type OrderStatus = 'pending' | 'confirmed' | 'priced' | 'assigned' | 'out_for_delivery' | 'delivered' | 'completed' | 'cancelled'
export type NotificationType = 'info' | 'success' | 'warning' | 'error'
export type DeliveryStatus = 'assigned' | 'picked_up' | 'in_transit' | 'delivered' | 'failed' | 'cancelled'

// Database structure following Supabase conventions
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          role: UserRole
          full_name: string | null
          restaurant_name: string | null
          phone: string | null
          address: string | null
          email?: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          role?: UserRole
          full_name?: string | null
          restaurant_name?: string | null
          phone?: string | null
          address?: string | null
          email?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          role?: UserRole
          full_name?: string | null
          restaurant_name?: string | null
          phone?: string | null
          address?: string | null
          email?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          name: string
          name_ka: string | null
          description: string | null
          description_ka: string | null
          price: number
          cost_price: number
          category: string
          unit: string
          stock_quantity: number
          min_stock_level: number
          image_url: string | null
          tags: string[] | null
          is_active: boolean
          is_available: boolean
          min_order_quantity?: number
          max_order_quantity?: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          name_ka?: string | null
          description?: string | null
          description_ka?: string | null
          price: number
          cost_price: number
          category: string
          unit: string
          stock_quantity?: number
          min_stock_level?: number
          image_url?: string | null
          tags?: string[] | null
          is_active?: boolean
          is_available?: boolean
          min_order_quantity?: number
          max_order_quantity?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          name_ka?: string | null
          description?: string | null
          description_ka?: string | null
          price?: number
          cost_price?: number
          category?: string
          unit?: string
          stock_quantity?: number
          min_stock_level?: number
          image_url?: string | null
          tags?: string[] | null
          is_active?: boolean
          is_available?: boolean
          min_order_quantity?: number
          max_order_quantity?: number
          created_at?: string
          updated_at?: string
        }
      }
      orders: {
        Row: {
          id: string
          restaurant_id: string
          driver_id: string | null
          status: OrderStatus
          total_amount: number | null
          delivery_fee: number | null
          tax_amount: number | null
          discount_amount: number | null
          delivery_address: string | null
          delivery_time: string | null
          delivery_notes: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          restaurant_id: string
          driver_id?: string | null
          status?: OrderStatus
          total_amount?: number | null
          delivery_fee?: number | null
          tax_amount?: number | null
          discount_amount?: number | null
          delivery_address?: string | null
          delivery_time?: string | null
          delivery_notes?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          restaurant_id?: string
          driver_id?: string | null
          status?: OrderStatus
          total_amount?: number | null
          delivery_fee?: number | null
          tax_amount?: number | null
          discount_amount?: number | null
          delivery_address?: string | null
          delivery_time?: string | null
          delivery_notes?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string
          quantity: number
          unit_price: number
          cost_price: number | null
          selling_price: number | null
          subtotal: number
          total_price: number
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          order_id: string
          product_id: string
          quantity: number
          unit_price: number
          cost_price?: number | null
          selling_price?: number | null
          subtotal: number
          total_price: number
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          product_id?: string
          quantity?: number
          unit_price?: number
          cost_price?: number | null
          selling_price?: number | null
          subtotal?: number
          total_price?: number
          notes?: string | null
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: NotificationType
          title: string
          title_ka: string | null
          message: string
          message_ka: string | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type?: NotificationType
          title: string
          title_ka?: string | null
          message: string
          message_ka?: string | null
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: NotificationType
          title?: string
          title_ka?: string | null
          message?: string
          message_ka?: string | null
          is_read?: boolean
          created_at?: string
        }
      }
      demo_sessions: {
        Row: {
          id: string
          session_id: string
          session_token: string
          user_id: string | null
          role: 'admin' | 'restaurant' | 'driver'
          started_at: string
          ended_at: string | null
          expires_at: string
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          session_token: string
          user_id?: string | null
          role: 'admin' | 'restaurant' | 'driver'
          started_at?: string
          ended_at?: string | null
          expires_at: string
          created_at?: string
        }
        Update: {
          id?: string
          session_id?: string
          session_token?: string
          user_id?: string | null
          role?: 'admin' | 'restaurant' | 'driver'
          started_at?: string
          ended_at?: string | null
          expires_at?: string
          created_at?: string
        }
      }
      order_status_history: {
        Row: {
          id: string
          order_id: string
          old_status: string | null
          new_status: string
          changed_by: string | null
          changed_at: string
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          order_id: string
          old_status?: string | null
          new_status: string
          changed_by?: string | null
          changed_at?: string
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          old_status?: string | null
          new_status?: string
          changed_by?: string | null
          changed_at?: string
          notes?: string | null
          created_at?: string
        }
      }
      order_audit_logs: {
        Row: {
          id: string
          order_id: string
          action: string
          details: Json | null
          metadata: Json | null
          performed_by: string | null
          created_at: string
          created_by: string
        }
        Insert: {
          id?: string
          order_id: string
          action: string
          details?: Json | null
          metadata?: Json | null
          performed_by?: string | null
          created_at?: string
          created_by: string
        }
        Update: {
          id?: string
          order_id?: string
          action?: string
          details?: Json | null
          metadata?: Json | null
          performed_by?: string | null
          created_at?: string
          created_by?: string
        }
      }
      deliveries: {
        Row: {
          id: string
          order_id: string
          driver_id: string
          status: DeliveryStatus
          pickup_time: string | null
          delivery_time: string | null
          estimated_delivery_time: string | null
          actual_delivery_time: string | null
          delivery_address: string
          delivery_coordinates: Json | null
          customer_name: string | null
          customer_phone: string | null
          special_instructions: string | null
          delivery_fee: number | null
          distance_km: number | null
          estimated_duration_minutes: number | null
          actual_duration_minutes: number | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          order_id: string
          driver_id: string
          status?: DeliveryStatus
          pickup_time?: string | null
          delivery_time?: string | null
          estimated_delivery_time?: string | null
          actual_delivery_time?: string | null
          delivery_address: string
          delivery_coordinates?: Json | null
          customer_name?: string | null
          customer_phone?: string | null
          special_instructions?: string | null
          delivery_fee?: number | null
          distance_km?: number | null
          estimated_duration_minutes?: number | null
          actual_duration_minutes?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          order_id?: string
          driver_id?: string
          status?: DeliveryStatus
          pickup_time?: string | null
          delivery_time?: string | null
          estimated_delivery_time?: string | null
          actual_delivery_time?: string | null
          delivery_address?: string
          delivery_coordinates?: Json | null
          customer_name?: string | null
          customer_phone?: string | null
          special_instructions?: string | null
          delivery_fee?: number | null
          distance_km?: number | null
          estimated_duration_minutes?: number | null
          actual_duration_minutes?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      policy_audit_log: {
        Row: {
          id: string
          table_name: string
          operation: string
          user_id: string | null
          row_id: string | null
          passed: boolean
          reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          table_name: string
          operation: string
          user_id?: string | null
          row_id?: string | null
          passed: boolean
          reason?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          table_name?: string
          operation?: string
          user_id?: string | null
          row_id?: string | null
          passed?: boolean
          reason?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      get_user_role: { Args: never; Returns: string }
      is_admin: { Args: never; Returns: boolean }
      is_driver: { Args: never; Returns: boolean }
      is_restaurant: { Args: never; Returns: boolean }
    }
    Enums: {
      notification_type: "info" | "success" | "warning" | "error"
      order_status: "pending" | "confirmed" | "priced" | "assigned" | "out_for_delivery" | "delivered" | "completed" | "cancelled"
      user_role: "admin" | "restaurant" | "driver" | "demo"
      delivery_status: "assigned" | "picked_up" | "in_transit" | "delivered" | "failed" | "cancelled"
    }
  }
}

// Type helpers for easier usage
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"]
export type Inserts<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"]
export type Updates<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"]

// Specific table types
export type Profile = Tables<"profiles">
export type Product = Tables<"products">
export type Order = Tables<"orders">
export type OrderItem = Tables<"order_items">
export type Notification = Tables<"notifications">
export type DemoSession = Tables<"demo_sessions">
export type OrderStatusHistory = Tables<"order_status_history">
export type OrderAuditLog = Tables<"order_audit_logs">
export type Delivery = Tables<"deliveries">
export type PolicyAuditLog = Tables<"policy_audit_log">

// Insert types
export type ProfileInsert = Inserts<"profiles">
export type ProductInsert = Inserts<"products">
export type OrderInsert = Inserts<"orders">
export type OrderItemInsert = Inserts<"order_items">
export type NotificationInsert = Inserts<"notifications">
export type DemoSessionInsert = Inserts<"demo_sessions">
export type OrderStatusHistoryInsert = Inserts<"order_status_history">
export type OrderAuditLogInsert = Inserts<"order_audit_logs">
export type DeliveryInsert = Inserts<"deliveries">

// Update types
export type ProfileUpdate = Updates<"profiles">
export type ProductUpdate = Updates<"products">
export type OrderUpdate = Updates<"orders">
export type OrderItemUpdate = Updates<"order_items">
export type NotificationUpdate = Updates<"notifications">
export type DemoSessionUpdate = Updates<"demo_sessions">
export type OrderStatusHistoryUpdate = Updates<"order_status_history">
export type OrderAuditLogUpdate = Updates<"order_audit_logs">
export type DeliveryUpdate = Updates<"deliveries">

// Extended types for complex queries
export interface OrderWithRelations extends Order {
  profiles?: {
    full_name: string
    restaurant_name?: string
  } | null
  deliveries?: Delivery[]
  order_items?: OrderItem[]
}

export interface ProductWithOrderItems extends Product {
  order_items?: OrderItem[]
}

// Supabase client type for convenience
export type SupabaseClient = Database
